INSERT INTO questions (question_id, question, answer, created_at, interview_id)
VALUES (1, 'What is polymorphism?', 'Polymorphism is a concept in object-oriented programming...', NOW(), 1),
       (2, 'What are design patterns?',
        'Design patterns are reusable solutions to common problems in software design...', NOW(), 1),
       (3, 'What is a deadlock?', 'A deadlock is a situation in which two or more processes are unable to proceed...',
        NOW(), 1),
       (4, 'Explain the SOLID principles.',
        'SOLID is an acronym for five design principles in object-oriented programming...', NOW(), 1),
       (5, 'What is dependency injection?',
        'Dependency injection is a design pattern in which an object receives other objects it depends on...', NOW(),
        1),
       (6, 'What is a RESTful API?',
        'A RESTful API is an application programming interface that uses HTTP requests to access and use data...',
        NOW(), 1),
       (7, 'Explain microservices architecture.',
        'Microservices architecture is a design pattern in which a system is divided into small services...', NOW(), 1),
       (8, 'What is continuous integration?',
        'Continuous integration is a DevOps practice in which developers regularly merge code changes into a shared repository...',
        NOW(), 1),
       (9, 'How does garbage collection work in Java?',
        'Garbage collection in Java is the process of automatically freeing memory...', NOW(), 1),
       (10, 'Explain the difference between an abstract class and an interface.',
        'An abstract class can have method implementations, while an interface can only have method signatures...',
        NOW(), 1),
       (11, 'What is a lambda expression?',
        'A lambda expression is a short block of code which takes in parameters and returns a value...', NOW(), 1),
       (12, 'What is a thread in programming?',
        'A thread is the smallest unit of a process that can be scheduled for execution...', NOW(), 1),
       (13, 'What is a mutex?',
        'A mutex is a synchronization primitive that is used to control access to a resource...', NOW(), 1),
       (14, 'Explain the difference between SQL and NoSQL databases.',
        'SQL databases are relational and use structured query language, while NoSQL databases are non-relational...',
        NOW(), 1),
       (15, 'What is the difference between black-box and white-box testing?',
        'Black-box testing tests the functionality without looking at the internal code, whereas white-box testing involves testing internal code structure...',
        NOW(), 1),
       (16, 'Explain the CAP theorem.',
        'The CAP theorem states that a distributed data store can only provide two out of the following three guarantees: Consistency, Availability, and Partition Tolerance...',
        NOW(), 1),
       (17, 'What is event-driven architecture?',
        'Event-driven architecture is a design pattern in which the system reacts to events or changes in state...',
        NOW(), 1),
       (18, 'What is the difference between monolithic and microservices architecture?',
        'Monolithic architecture is a single, unified system, while microservices architecture splits the system into smaller, independent services...',
        NOW(), 1),
       (19, 'Explain the concept of Agile development.',
        'Agile development is a project management methodology that involves iterative development, where requirements and solutions evolve through collaboration...',
        NOW(), 1),
       (20, 'What is a relational database?',
        'A relational database is a type of database that stores and provides access to data points that are related to one another...',
        NOW(), 1),
       (21, 'Explain what a foreign key is in a database.',
        'A foreign key is a column or group of columns in a relational database table that provides a link between data in two tables...',
        NOW(), 1),
       (22, 'What is a stored procedure?',
        'A stored procedure is a prepared SQL code that you can save, so the code can be reused over and over again...',
        NOW(), 1);

INSERT INTO questions (question_id, question, answer, created_at, interview_id)
VALUES (23, 'Tell me about yourself.', 'I am a dedicated software engineer with a passion for technology...', NOW(), 2),
       (24, 'Why do you want to work here?',
        'I am impressed by the company’s mission and values, and I believe my skills would be a great fit...', NOW(),
        2),
       (25, 'What are your greatest strengths?',
        'My greatest strengths are problem-solving, adaptability, and effective communication...', NOW(), 2),
       (26, 'What are your weaknesses?',
        'I sometimes get too focused on details, but I am working on improving my time management skills...', NOW(), 2),
       (27, 'Describe a time when you faced a challenge at work.',
        'At my previous job, I was tasked with leading a team under tight deadlines...', NOW(), 2),
       (28, 'How do you handle stress and pressure?',
        'I manage stress by staying organized and prioritizing tasks effectively...', NOW(), 2),
       (29, 'Why are you leaving your current job?', 'I am looking for new challenges and opportunities for growth...',
        NOW(), 2),
       (30, 'What are your career goals?',
        'My career goals include advancing into a leadership role while continuing to develop my technical skills...',
        NOW(), 2),
       (31, 'How do you prioritize your work?',
        'I use a combination of task lists and time management techniques to prioritize my work...', NOW(), 2),
       (32, 'How do you handle constructive criticism?',
        'I appreciate constructive criticism as it helps me grow and improve in my role...', NOW(), 2),
       (33, 'What motivates you?',
        'I am motivated by continuous learning and the satisfaction of solving challenging problems...', NOW(), 2),
       (34, 'How do you work in a team?',
        'I believe in clear communication and collaboration to achieve the team’s goals...', NOW(), 2),
       (35, 'What is your greatest achievement?',
        'My greatest achievement was leading a team that delivered a critical project ahead of schedule...', NOW(), 2),
       (36, 'Describe a time when you went above and beyond at work.',
        'There was a situation where I stayed late to help a colleague finish a project on time...', NOW(), 2),
       (37, 'How do you handle conflicts at work?',
        'I address conflicts by remaining calm, listening to all sides, and finding a compromise...', NOW(), 2),
       (38, 'What do you expect from a manager?',
        'I expect clear communication, regular feedback, and support in achieving my professional goals...', NOW(), 2),
       (39, 'How do you stay organized?',
        'I stay organized by using task management tools and regularly updating my progress...', NOW(), 2),
       (40, 'What do you enjoy doing outside of work?',
        'I enjoy hiking, reading, and learning about new technologies...', NOW(), 2),
       (41, 'Where do you see yourself in 5 years?',
        'In five years, I see myself in a leadership position with a deeper understanding of software architecture...',
        NOW(), 2),
       (42, 'What are your salary expectations?',
        'I am looking for a competitive salary that reflects my experience and skills...', NOW(), 2),
       (43, 'Why should we hire you?',
        'You should hire me because I have the skills, experience, and passion to contribute effectively to your team...',
        NOW(), 2),
       (44, 'Do you have any questions for us?', 'Yes, could you tell me more about the team I would be working with?',
        NOW(), 2);
